apiVersion: v1
kind: Pod
metadata:
  labels:
    application: location-service
  name: location-service
spec:
  containers:
  - image: cshrrpg.azurecr.io/location-service
    name: location-service
    livenessProbe:
      httpGet:
        path: /
        port: 8989
      initialDelaySeconds: 30
      periodSeconds: 3
    resources:
      limits:
        memory: "700Mi"
    env:
    - name: LOCATION_SERVICE_GOOGLE_SERVICE_API_KEY
      value: "AIzaSyDw51wA5CgK-bf0eIyPY_-e8qMh5fu-Vsc"
    ports:
    - containerPort: 8989
      protocol: TCP
  
